---
title: " Project 1"
author: "Sanchit Vijay"
date: "2022-10-19"
output: html_document
---
```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
library(tidyverse)
library(ggplot2)
library(dplyr)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```


```{r, results='markup'}
#First, load the file
zillow = data.frame(read.csv("price.csv"))
# head(zillow)
```


```{r, results='markup'}
# colSums(is.na(zillow))
summary(zillow)
zillow = na.omit(zillow)
# colSums(is.na(zillow))
# zillow
```

```{r, results='markup', fig.align="center", fig.width = 10, fig.height=5}
options(repr.plot.width=30, repr.plot.height=10)

ggplot(zillow, aes(x=State)) + geom_bar(colour="blue", fill="purple", alpha=0.6)
```


```{r, results='markup', fig.align="center", fig.width = 8, fig.height=5}
library("zoo")
library(ggfortify)
library(reshape2)

num_city = 10
values=head(zillow, num_city)
values=data.frame(t(as.matrix(values[,7:81])))
colnames(values)=zillow[1:num_city,2]

date <- seq(as.Date("2010/11/01"), as.Date("2017/01/31"), "month")
date <- as.yearmon(date)
ts=zoo(values,order.by = date)
values=fortify(ts)
values$Index=as.Date(values$Index)

autoplot(ts,facet=NULL, )+
  theme_minimal()+
  labs(x="Time",y="Price")
# Y = cbind(values[,grepl("X", colnames(values))])
# ne = melt(values, id = 'Index')#, variable.name = 'series')
# ne
# ts
# ggplot(ne, aes(x=Index, y=value)) + geom_line()

```

```{r, results='markup', fig.align="center", fig.width = 10, fig.height=5}
price <- gather(data = zillow, "Month", "Price", 7:81, factor_key = T)

plot1 <- ggplot(price[price$State == "CA" & !is.na(price$Metro),]) +
  geom_boxplot(aes(x = fct_rev(Metro), 
                   y = as.numeric(Price)), fill="#FF9999", color="#56B4E9", outlier.size = 0.5) +
  labs(x = "Metro Area", y = "Price", #note these are opposite because I use coord_flip to flip the axes
       colour = "#E0E0E0") +
  theme(axis.ticks.y = element_blank(),
        plot.title = element_text(size = 15, face = c("bold","italic")),
        axis.text.x = element_text(size = 9),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        legend.position = "none",
        plot.subtitle = element_text(size = 10),
        plot.background = element_rect(fill = "white"), # background color
        panel.grid.major.y = element_line(color = "#E0E0E0"), # horizontal line color
        panel.background = element_rect(fill = "white")) +
  coord_flip()
plot1

```
```{r, results='markup', fig.width = 10, fig.height = 7}
plot2 <- ggplot(price[price$County == "Dallas" & !is.na(price$City),], 
               aes(y = fct_rev(City), x = Price)) +
  labs(title = "Zillow | San Diego County Rent Prices",
       subtitle = "2010 - 2017", 
       x = "Price", y = "County", 
       colour = "#E0E0E0") +
  geom_point(shape = 20, alpha = 0.4, size = 3, aes(color = Month)) +
  scale_color_discrete(l = 45, h = c(30, 330)) +
  theme(axis.ticks.y = element_blank(),
        plot.title = element_text(size = 15, face = c("bold","italic")),
        axis.text.x = element_text(size = 9),
        axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        legend.position = "none",
        plot.subtitle = element_text(size = 10),
        plot.background = element_rect(fill = "white"), # background color
        panel.grid.major.y = element_line(color = "#E0E0E0"), # horizontal line color
        panel.background = element_rect(fill = "white")) +
  scale_x_continuous(breaks = waiver()) #sets # of labels on x axis
plot2
```

```{r, results='markup'}
# nov = zillow[,grepl("Nov", colnames(zillow))]
# nov["city"] = zillow$City
# # nov
# ggplot(nov[1:10, ], aes(city, November.2010)) + 
#   geom_line()
```

```{r}
# library(forecast)
# forecasts=matrix(,ncol=10,nrow=11)
# 
# for(i in 1:10){
#   
#   forecasts[,i]=forecast(auto.arima(ts[,i],lambda = 0,stepwise = F),h=11)$mean
#   
# }
# # forecasts
# colnames(forecasts)=zillow[1:10,2]
# 
# results=rbind(values[,2:11],forecasts)
# date_2 <- seq(as.Date("2010/11/01"), as.Date("2017/12/31"),"month")
# date_2 <- as.yearmon(date_2)
# results=zoo(results,order.by = date_2)
# autoplot(results,facet=NULL)+
#   theme_minimal()+
#   labs(x="Time",y="Price")+
#   geom_vline(aes(xintercept=2017),size=0.2)
```

